import("//build_overrides/build.gni")
import("//build_overrides/chip.gni")

config("matter_controller_config") {
  include_dirs = [ "include" ]
}

static_library("matter_controller") {
  output_name = "matter_controller"
  complete_static_lib = true

  sources = [
    "src/matter_controller.cpp",
  ]

  public_configs = [ ":matter_controller_config" ]

  public_deps = [
    "${chip_root}/src/controller",
    "${chip_root}/src/controller/data_model",
    "${chip_root}/src/credentials:default_attestation_verifier",
    "${chip_root}/src/app",
    "${chip_root}/src/lib",
    "${chip_root}/src/platform",
    "${chip_root}/src/platform/logging:default",
    "${chip_root}/src/crypto",
    "${chip_root}/src/transport",
    "${chip_root}/src/protocols",
    "${chip_root}/src/ble",
  ]

  cflags = [ "-Wno-unused-parameter" ]
}
