/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: bridge/bridge.i

#ifndef SWIG_bridge_WRAP_H_
#define SWIG_bridge_WRAP_H_

class Swig_memory;

class SwigDirector_Callback : public Callback
{
 public:
  SwigDirector_Callback(int swig_p);
  virtual ~SwigDirector_Callback();
  void _swig_upcall_status(int status) {
    Callback::status(status);
  }
  virtual void status(int status);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
