/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: Bridge.i

#ifndef SWIG_Bridge_WRAP_H_
#define SWIG_Bridge_WRAP_H_

class Swig_memory;

class SwigDirector_Bridge : public Bridge
{
 public:
  SwigDirector_Bridge(int swig_p);
  virtual ~SwigDirector_Bridge();
  void _swig_upcall_cb() {
    Bridge::cb();
  }
  virtual void cb();
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
